apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podtato-head-tenant1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: podtato-head-tenant1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: podtato-head
    repoURL: https://github.com/jkleinlercher/keptn-argo-dev
    targetRevision: main
