stage: hardening

namespaces:
  - podtato-head-tenant1-hardening-1
  - podtato-head-tenant2-hardening-1

applications:
  podtato-head-tenant1-hardening-1:
    destination:
      namespace: podtato-head-tenant1-hardening-1
      server: https://kubernetes.default.svc
    project: default
    source:
      path: podtato-head
      repoURL: https://github.com/jkleinlercher/keptn-argo-dev
      targetRevision: hardening
      extraSourceFields: |
        helm:
          valueFiles:
          - values.yaml
  podtato-head-tenant2-hardening-1:
    destination:
      namespace: podtato-head-tenant2-hardening-1
      server: https://kubernetes.default.svc
    project: default
    source:
      path: podtato-head
      repoURL: https://github.com/jkleinlercher/keptn-argo-dev
      targetRevision: hardening
      extraSourceFields: |
        helm:
          valueFiles:
          - values.yaml