stage: dev

namespaces:
  - podtato-head-tenant1-dev-1
  - podtato-head-tenant2-dev-1
  - klej-test

applications:
  podtato-head-tenant1-dev-1:
    destination:
      namespace: podtato-head-tenant1-dev-1
      server: https://kubernetes.default.svc
    project: default
    source:
      path: podtato-head
      repoURL: https://github.com/jkleinlercher/keptn-argo-dev
      targetRevision: dev
      extraSourceFields: |
        helm:
          valueFiles:
          - values.yaml
    enableAutoSync: true
  podtato-head-tenant2-dev-1:
    destination:
      namespace: podtato-head-tenant2-dev-1
      server: https://kubernetes.default.svc
    project: default
    source:
      path: podtato-head
      repoURL: https://github.com/jkleinlercher/keptn-argo-dev
      targetRevision: dev
      extraSourceFields: |
        helm:
          valueFiles:
          - values.yaml
    enableAutoSync: true
