apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-apps-hardening-1
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-out-of-sync-status.keptn: ""
    notifications.argoproj.io/subscribe.on-deployed.keptn: ""
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    stage: hardening
    keptnService: all-apps
    keptnProject: argo-demo
spec:
  destination:
    namespace: "*"
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps
    repoURL: https://github.com/jkleinlercher/keptn-argo-dev
    targetRevision: hardening
    helm:
      valueFiles:
        - values-hardening-1-apps.yaml